### ISSUE TITLE
java.lang.IllegalArgumentException: Session token required (in moquiSessionToken)

### ISSUE THREAD

**Issue by ashokraman** [moqui/PopCommerce#21]
I am working with 1.6.1 all components, gradle 2.9, java 1.8, windows 10. 
Directly from the popc menu, if I add to cart one of the demo products go to check out and then log in as john.doe, I get this error - 
"
java.lang.IllegalArgumentException: Session token required (in moquiSessionToken) for URL http://localhost:8080/popc/Login/login
	at org.moqui.impl.screen.ScreenRenderImpl.internalRender(ScreenRenderImpl.groovy:297)
	at org.moqui.impl.screen.ScreenRenderImpl.render(ScreenRenderImpl.groovy:158)
	at org.moqui.impl.webapp.MoquiServlet.doScreenRequest(MoquiServlet.groovy:73)
	at org.moqui.impl.webapp.MoquiServlet.doPost(MoquiServlet.groovy:39)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:713)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
	at net.winstone.core.ServletConfiguration.execute(ServletConfiguration.java:270)
	at net.winstone.core.SimpleRequestDispatcher.forward(SimpleRequestDispatcher.java:290)
	at net.winstone.core.listener.RequestHandlerThread.processRequest(RequestHandlerThread.java:212)
	at net.winstone.core.listener.RequestHandlerThread.run(RequestHandlerThread.java:143)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.winstone.util.BoundedExecutorService$1.run(BoundedExecutorService.java:81)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
"
I kind of guessed it could be vestiges of the previous release, cleaned up my Local\Temp etc.
I also replaced framework with the latest from github for a quick check.
 
Thanks,
Ashok

**Comment by jonesde** [comment]
This is fixed in commit #2de2ab1. The login transition no longer requires a session token, just like in the Login.xml screen in webroot.

**Comment by locnguyenx** [comment]
I have similar exception with transition createAccount:
`java.lang.IllegalArgumentException: Session token required (in moquiSessionToken) for URL http://localhost:8080/popc/Login/createAccount`

I guess the same solution should be applied with this transition.

**Comment by jonesde** [comment]
In commit #fe29cea I changed those as well, did along with a bunch of html/style updates to cleanup the ecommerce app in PopCommerce after the recent changes in moqui-runtime.
